version: "3"
services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - ./sonar.properties:/opt/sonarqube/conf/sonar.properties
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
volumes:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
